name: School Management System Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.GA_USERNAME }}
          port: ${{ secrets.GA_PORT }}
          key: ${{ secrets.GA_KEY }}
          source: "./*"
          target: "/home/github/soar/source"
          rm: true

      - name: Signal updated source code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.GA_USERNAME }}
          port: ${{ secrets.GA_PORT }}
          key: ${{ secrets.GA_KEY }}
          script: echo 1 > /home/github/soar/semaphore
